version: "3.9"

services:
    server:
        container_name: server
        image: server
        restart: always
        build:
            context: .
            dockerfile: dockerfile
            target: base
        ports:
            - 3000:3000